### ISSUE TITLE
Correções no readme.md

### ISSUE THREAD

**Issue by OctavioArruda** [marcoshenrique-dev/api-contacts#1]
Boa noite. Vi seu post no linkedin e achei muito bacana que nessa idade você esteja se esforçando para aprender tanto inglês quanto programação. Caso tenha interesse, fiz a parte do texto do readme um pouco mais "ajeitada"(mais correta sintática e semanticamente).

Ficaria assim:

# Api-Contacts

* This application is the result of the course devBoost, an incredible learning and studying experience on Postgres, Node and Design Patterns.

* Until now I've learned about the ESLint configuration, EditorConfig and Design Patterns like Singleton and Repository.

## How to install?

* Clone the repo and run the command `yarn` or `npm install`.
* Run `yarn dev` or `npm run dev` to start the application.

O código do markdown: 
```# Api-Contacts

* This application is the result of the course devBoost, an incredible learning and studying experience on Postgres, Node and design Patterns.

* Until now I've learned about the ESLint configuration, EditorConfig and Design Patterns like Singleton and Repository patterns.

## How to install?

* Clone the repo and run the command `yarn` or `npm install`.
* Run `yarn dev` or `npm run dev` to start the application.
```

Observação: Esses asteríscos e hashtags fazem parte da formatação dos arquivos .md (MarkDown). 
Recomendo esse site para praticas MarkDown: https://stackedit.io/ , onde você pode escrever e ver o resultado ao lado.

**Comment by marcoshenrique-dev** [comment]
Obrigado pela ajuda! Vou fazer a alteração :)
